version: '3.8'

services:
  bipal-backend:
    image: bipal-backend:latest
    container_name: bipal-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - /var/log/bipal:/logs
    networks:
      - qa-net
      - bipal-network

networks:
  qa-net:
    external: true
  bipal-network:
    driver: bridge
