name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - pipeline
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  build-and-deploy:
    # Solo ejecutar el workflow si el PR fue merged o estamos en la rama pipeline
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Compilar con Maven
        run: mvn -B clean package -DskipTests
      
      # - name: Ejecutar tests
      #   run: mvn -B test
      
      - name: Construir imagen Docker
        run: |
          docker build -t bipal-backend:${{ github.sha }} .
          docker tag bipal-backend:${{ github.sha }} bipal-backend:latest
      
      - name: Guardar imagen Docker
        run: |
          mkdir -p ./docker-image
          docker save bipal-backend:latest > ./docker-image/bipal-backend.tar
      
      - name: Guardar imagen como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ./docker-image/bipal-backend.tar
          retention-days: 1
      
# TODO: configurar usuario del servidor
      # - name: Desplegar en servidor
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     source: "./docker-image/bipal-backend.tar,./.github/deploy.sh"
      #     target: "/tmp/bipal-deploy"
      
      # - name: Ejecutar despliegue
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     envs: DB_URL,DB_USERNAME,DB_PASSWORD,JWT_SECRET
      #     script: |
      #       cd /tmp/bipal-deploy
      #       chmod +x deploy.sh
      #       ./deploy.sh
